language: ruby
cache: bundler
before_install: gem update --remote bundler
jobs:
  include:
    - stage: Rake
      before_scropt:
        - bundle exec rake db:schema:load
        - bundle exec rake db:test:prepare
      script: bundle exec rake
    - stage: Rubucop
      script: bundle exec rubocop

services:
  - postgresql
