language: ruby
cache: bundler
services:
  - postgresql
before_install: gem update --no-document --remote bundler
before_script: bundle exec rake db:test:prepare
script: 
  - bundle exec rake
  - bundle exec rubocop
