language: ruby
addons:
  postgresql: "10"
dist: bionic
cache:
  bundler: true
  directories:
  - node_modules
services:
- postgresql
before_install:
- gem update --no-document --remote bundler
- yarn install
before_script:
- rm -rf public/packs*/
- ./bin/rake db:test:prepare
- RAILS_ENV=test ./bin/rails webpacker:compile
script:
- ./bin/rake
- ./bin/rubocop
deploy:
  provider: script
  skip_cleanup: true
  script: rvm use $TRAVIS_RUBY_VERSION do ./bin/deploy.sh
  on:
    branch: master
    # condition: "$TRAVIS_COMMIT_MESSAGE" =~ Release
