defaults: &defaults
  default_url_options: &default_url_options
    host: <%= ENV['APP_HOST'] || 'localhost' %>

  mailer:
    from: Tasky <no-reply@tasky.online>
  
  sidekiq_redis:
    url:       redis://localhost:6379/6

staging:
  <<: *defaults
  default_url_options: 
    host: tasky.brandymint.ru

production:
  <<: *defaults
  default_url_options: 
    host: tasky.online

development:
  <<: *defaults

test:
  <<: *defaults
  default_url_options: &default_url_options
    host: <%= ENV['APP_HOST'] || 'test.host' %>
