defaults: &defaults
  default_url_options: &default_url_options
    host: <%= ENV['APP_HOST'] || 'localhost' %>

  mailer:
    from: no-reply@tasky.online

staging:
  <<: *defaults
  default_url_options: 
    host: tasky.brandymint.ru

production:
  <<: *defaults
  default_url_options: 
    host: tasky.online

development:
  <<: *defaults

test:
  <<: *defaults
  default_url_options: &default_url_options
    host: <%= ENV['APP_HOST'] || 'test.host' %>
